-- MySQL Script generated by MySQL Workbench
-- Sat 05 Mar 2022 12:17:15 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_469493
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_469493
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_469493` ;
USE `db_469493` ;

-- -----------------------------------------------------
-- Table `db_469493`.`SEASONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`SEASONS` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`SEASONS` (
  `id_season` INT NOT NULL AUTO_INCREMENT,
  `season_name` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `begin_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `entrance_fee` DOUBLE NOT NULL,
  PRIMARY KEY (`id_season`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`FACTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`FACTIONS` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`FACTIONS` (
  `id_faction` INT NOT NULL AUTO_INCREMENT,
  `faction_name` VARCHAR(50) NOT NULL,
  `faction_god` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `id_player_faction_king` INT NOT NULL,
  `faction_kills` INT NOT NULL DEFAULT 0,
  `faction_karma` INT NOT NULL,
  `faction_power` INT NOT NULL,
  PRIMARY KEY (`id_faction`),
  INDEX `FK_FACTIONS_PLAYERS_idx` (`id_player_faction_king` ASC),
  CONSTRAINT `FK_FACTIONS_PLAYERS`
    FOREIGN KEY (`id_player_faction_king`)
    REFERENCES `db_469493`.`PLAYERS` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`PLAYERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`PLAYERS` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`PLAYERS` (
  `id_player` INT NOT NULL AUTO_INCREMENT,
  `id_season` INT NOT NULL,
  `id_faction` INT NOT NULL,
  `UUID` VARCHAR(500) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `player_name` VARCHAR(500) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `discord_tag` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NULL,
  `kills` INT NOT NULL DEFAULT 0,
  `email` VARCHAR(200) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NULL,
  `ip_public_4` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `ip_public_6` VARCHAR(200) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  PRIMARY KEY (`id_player`),
  INDEX `FK_SEASONS_PLAYERS_idx` (`id_season` ASC),
  INDEX `FK_PLAYERS_FACTIONS_idx` (`id_faction` ASC),
  CONSTRAINT `FK_SEASONS_PLAYERS`
    FOREIGN KEY (`id_season`)
    REFERENCES `db_469493`.`SEASONS` (`id_season`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLAYERS_FACTIONS`
    FOREIGN KEY (`id_faction`)
    REFERENCES `db_469493`.`FACTIONS` (`id_faction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`ROLES` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`ROLES` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `max_rol_faction` INT NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`PERMISSIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`PERMISSIONS` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`PERMISSIONS` (
  `id_permission` INT NOT NULL AUTO_INCREMENT,
  `id_role` INT NOT NULL,
  `can_build` TINYINT NOT NULL,
  `can_access_assests` TINYINT NOT NULL,
  `can_claim` TINYINT NOT NULL,
  `can_diplomacy` TINYINT NOT NULL,
  `can_enhance` TINYINT NOT NULL,
  `can_craft_weapons` TINYINT NOT NULL,
  `can_craft_tools` TINYINT NOT NULL,
  `can_brew` TINYINT NOT NULL,
  PRIMARY KEY (`id_permission`),
  INDEX `FK_ROLES_PERMISSIONS_idx` (`id_role` ASC),
  CONSTRAINT `FK_ROLES_PERMISSIONS`
    FOREIGN KEY (`id_role`)
    REFERENCES `db_469493`.`ROLES` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`CLAIMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`CLAIMS` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`CLAIMS` (
  `id_claim` INT NOT NULL,
  `id_faction` INT NOT NULL,
  `from` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `to` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `influence` INT NOT NULL,
  `is_main` TINYINT NOT NULL,
  PRIMARY KEY (`id_claim`),
  INDEX `FK_FACTIONS_CLAIMS_idx` (`id_faction` ASC),
  CONSTRAINT `FK_FACTIONS_CLAIMS`
    FOREIGN KEY (`id_faction`)
    REFERENCES `db_469493`.`FACTIONS` (`id_faction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`ASSESTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`ASSESTS` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`ASSESTS` (
  `id_asset` INT NOT NULL AUTO_INCREMENT,
  `id_faction` INT NOT NULL,
  `id_item` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id_asset`),
  INDEX `FK_FACTIONS_ASSESTS_idx` (`id_faction` ASC),
  CONSTRAINT `FK_FACTIONS_ASSESTS`
    FOREIGN KEY (`id_faction`)
    REFERENCES `db_469493`.`FACTIONS` (`id_faction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`DIPLOMACY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`DIPLOMACY` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`DIPLOMACY` (
  `id_diplomacy` INT NOT NULL AUTO_INCREMENT,
  `id_season` INT NOT NULL,
  `id_faction_from` INT NOT NULL,
  `id_faction_to` INT NOT NULL,
  `factor` DOUBLE NOT NULL,
  PRIMARY KEY (`id_diplomacy`),
  INDEX `FK_SEASON_DIPLOMACY_idx` (`id_season` ASC),
  INDEX `FK_FACTIONS_FROM_DIPLOMACY_idx` (`id_faction_from` ASC),
  INDEX `FK_FACTIONS_TO_DIPLOMACY_idx` (`id_faction_to` ASC),
  CONSTRAINT `FK_SEASON_DIPLOMACY`
    FOREIGN KEY (`id_season`)
    REFERENCES `db_469493`.`SEASONS` (`id_season`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FACTIONS_FROM_DIPLOMACY`
    FOREIGN KEY (`id_faction_from`)
    REFERENCES `db_469493`.`FACTIONS` (`id_faction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FACTIONS_TO_DIPLOMACY`
    FOREIGN KEY (`id_faction_to`)
    REFERENCES `db_469493`.`FACTIONS` (`id_faction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_469493`.`PLAYERS_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_469493`.`PLAYERS_ROLES` ;

CREATE TABLE IF NOT EXISTS `db_469493`.`PLAYERS_ROLES` (
  `id_player` INT NOT NULL,
  `id_role` INT NOT NULL,
  `date_assign` DATETIME NOT NULL,
  PRIMARY KEY (`id_player`, `id_role`),
  INDEX `FK_PLAYERS_ROLES_idx` (`id_role` ASC),
  CONSTRAINT `FK_PLAYERS_ROLES_ROLES`
    FOREIGN KEY (`id_role`)
    REFERENCES `db_469493`.`ROLES` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLAYERS_ROLES_PLAYERS`
    FOREIGN KEY (`id_player`)
    REFERENCES `db_469493`.`PLAYERS` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
